# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.runs/synth_1/RV64IM72F6SP_CORE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.cache/wt [current_project]
set_property parent.project_path /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/alu_op.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/rtype_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/branch_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/rtype_mul_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/opcode.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/itype_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/csr_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/store_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/load_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/alu_src_select.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/rf_wd_select.vh
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/headers/trap.vh
}
read_mem {
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/benchmarks/dhrystone.mem
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/benchmarks/coremark.mem
}
read_verilog -library xil_defaultlib {
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/ALU.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/ALU_Controller.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/ALU_DWORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/ALU_WORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Branch_Logic.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Branch_Predictor.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Byte_Enable_Logic.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/CSR_File.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Control_Unit.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Divider_DWORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Divider_WORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/EX_EX2_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/EX_MEM_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Exception_Detector.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Forward_Unit.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Hazard_Unit.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/ID_EX_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/IF_IO_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/IO_ID_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Immediate_Generator.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Instruction_Decoder.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/MEM_WB_Register.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Multiplier_DWORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Multiplier_WORD.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/PC_Controller.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/PC_Plus_4.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Program_Counter.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Register_File.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/Trap_Controller.v
  /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/sources_1/imports/FPGA_SoC/modules/RV64IM72F_6SP.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/constrs_1/imports/FPGA_SoC/RV32I46F_5SP_Debug_XDC.xdc
set_property used_in_implementation false [get_files /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/constrs_1/imports/FPGA_SoC/RV32I46F_5SP_Debug_XDC.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/khwl/Desktop/RV-IM100/RV64s/RV64IM_7SP_BRAM/RV64IM72F_7SP_FPGA.srcs/utils_1/imports/synth_1/RV64IM72F5SPSoCTOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RV64IM72F6SP_CORE -part xc7a200tsbg484-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5 -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV64IM72F6SP_CORE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file RV64IM72F6SP_CORE_utilization_synth.rpt -pb RV64IM72F6SP_CORE_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
