# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.runs/synth_1/RV32IM72F5SP_CORE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-158854-khwl-main-pc/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.cache/wt [current_project]
set_property parent.project_path /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/alu_op.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/rtype_mul_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/opcode.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/itype_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/rtype_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/branch_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/csr_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/store_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/load_funct3.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/alu_src_select.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/rf_wd_select.vh
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/headers/trap.vh
}
read_mem {
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/coremark.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/dhrystone.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/dhrystone_RV64IM_38MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/dhrystone_RV64IM_40MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/dhrystone_RV64IM_39MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/coremark_RV64IM_40MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/coremark_RV64IM_39MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64s/coremark_RV64IM_38MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/dhrystones/dhrystone_RV32IM_38MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/dhrystones/dhrystone_RV32IM_38MHz_comp.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/benchmarks/coremarks/coremark_RV32IM_43MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/benchmarks/dhrystones/dhrystone_RV32IM_43MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/benchmarks/coremarks/coremark_RV32IM_42.5MHz.mem
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/benchmarks/dhrystones/dhrystone_RV32IM_42.5MHz.mem
}
read_verilog -library xil_defaultlib {
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/ALU.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/ALU_Controller.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/ALU_WORD.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Branch_Logic.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Branch_Predictor.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Byte_Enable_Logic.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/CSR_File.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Control_Unit.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Divider_WORD.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/EX_MEM_Register.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Exception_Detector.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Forward_Unit.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Hazard_Unit.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/ID_EX_Register.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/IF_ID_Register.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Immediate_Generator.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Instruction_Decoder.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/MEM_WB_Register.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Multiplier_WORD.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/PC_Controller.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/PC_Plus_4.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Program_Counter.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Register_File.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/Trap_Controller.v
  /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/sources_1/imports/RV64IM72F_5SP/RV64IM72F_5SP.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/constrs_1/imports/RV64IM72F_5SP/RV32I46F_5SP_Debug_XDC.xdc
set_property used_in_implementation false [get_files /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/constrs_1/imports/RV64IM72F_5SP/RV32I46F_5SP_Debug_XDC.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/khwl/Desktop/RV-IM100/RV32s/cores/RV32IM_5SP/RV64IM72F_5SP_FPGA.srcs/utils_1/imports/synth_1/RV64IM72F5SPSoCTOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RV32IM72F5SP_CORE -part xc7a200tsbg484-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5 -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV32IM72F5SP_CORE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file RV32IM72F5SP_CORE_utilization_synth.rpt -pb RV32IM72F5SP_CORE_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
