#!/usr/bin/env python3
"""Research_data_RISCOF_with_cores_0902.xlsx -> Research_data_complete_0908.xlsx

Each SoC project is implemented with ONE benchmark image in ROM, and the image
changes the LUT count -- which is why the workbook keeps a separate "SoC
Dhrystone" and "SoC Coremark" block.  The Sep 8 sweep measured whatever image
each project currently holds, so each variant updates exactly one row, in
whichever block matches its image.  Rows in the other block keep their Sep 1/2
values and are labelled as such rather than being overwritten with a number
that was never measured for that image.
"""
import csv, json, pathlib, shutil, datetime
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment

ENV  = pathlib.Path(__file__).resolve().parent.parent
SRC  = pathlib.Path.home() / "Documents" / "Research_data_RISCOF_with_cores_0902.xlsx"
DST  = pathlib.Path.home() / "Documents" / "Research_data_complete_0913.xlsx"
CSV  = ENV / "logs" / "impl_retime.csv"

# Each SoC project holds ONE benchmark image, and the image changes the design,
# so the workbook keeps a "SoC Dhrystone" block (rows 13-20) and a "SoC Coremark"
# block (rows 23-30).  A variant sits in whichever block matches the image it
# holds; swapping the image moves it to the mirrored row, ten rows away.
#
# PRE  = measured 2026-09-08 with the image each project held then.
# POST = measured 2026-09-09 after swapping every project to the other benchmark.
# Both are real measurements, so both blocks are populated.
# the pre-swap CSV kept only the workbook columns; clock and WNS come from the
# verified Sep-8 figures recorded in STATUS.md
pre_clk = {"RV32I_5SP":45.0,"RV32IM_5SP":43.0,"RV32IM_6SP":50.0,"RV32IM_7SP":58.0,
 "RV32IM_7SP_BRAM":72.0,"RV32IM_7SP_BRAM_Opt":90.909,"RV32IM_8SP_withoutOpt":114.0,
 "RV32IM_8SP":125.0,"RV64I_5SP":40.0,"RV64IM_5SP":38.0,"RV64IM_6SP":45.0,
 "RV64IM_7SP":48.612,"RV64IM_7SP_BRAM":55.0,"RV64IM_7SP_BRAM_Opt":84.0,
 "RV64IM_8SP_withoutOpt":96.0,"RV64IM_8SP":100.0}
pre_wns = {"RV32I_5SP":0.137,"RV32IM_5SP":0.074,"RV32IM_6SP":0.028,"RV32IM_7SP":-0.005,
 "RV32IM_7SP_BRAM":0.091,"RV32IM_7SP_BRAM_Opt":0.092,"RV32IM_8SP_withoutOpt":0.023,
 "RV32IM_8SP":-0.223,"RV64I_5SP":0.052,"RV64IM_5SP":0.040,"RV64IM_6SP":0.053,
 "RV64IM_7SP":-0.242,"RV64IM_7SP_BRAM":0.239,"RV64IM_7SP_BRAM_Opt":0.003,
 "RV64IM_8SP_withoutOpt":-0.444,"RV64IM_8SP":0.160}

PRE = {
    "RV64I_5SP":            ("Sheet1", 13), "RV64IM_7SP_BRAM_Opt": ("Sheet1", 18),
    "RV64IM_8SP":           ("Sheet1", 20), "RV64IM_5SP":          ("Sheet1", 24),
    "RV64IM_6SP":           ("Sheet1", 25), "RV64IM_7SP":          ("Sheet1", 26),
    "RV64IM_7SP_BRAM":      ("Sheet1", 27), "RV64IM_8SP_withoutOpt": ("Sheet1", 29),
    "RV32IM_5SP":           ("Sheet2", 14), "RV32IM_7SP_BRAM":     ("Sheet2", 17),
    "RV32IM_7SP_BRAM_Opt":  ("Sheet2", 18), "RV32IM_8SP_withoutOpt": ("Sheet2", 19),
    "RV32IM_8SP":           ("Sheet2", 20), "RV32I_5SP":           ("Sheet2", 23),
    "RV32IM_6SP":           ("Sheet2", 25), "RV32IM_7SP":          ("Sheet2", 26),
}
mirror = lambda r: r + 10 if r <= 20 else r - 10

COL = dict(lut="C", lutram="D", ff="E", bram="F", dsp="G", io="H", pll="I", fmax="J",
           p_clocks="M", p_signals="N", p_logic="O", p_bram="P", p_dsp="Q",
           p_pll="R", p_io="S", p_static="T", note="U")

# Colour only where there is something to act on.  A fill on every row -- the old
# green-for-normal -- is noise: it makes the sheet look busy and hides the rows
# that actually need attention.
RED   = PatternFill("solid", fgColor="FFC7CE")   # timing VIOLATION at the configured clock
BLUE  = PatternFill("solid", fgColor="BDD7EE")   # >1 MHz headroom: build a faster .mem
GREEN = PatternFill(fill_type=None)              # timing met, nothing to do -> no fill
GREY  = PatternFill("solid", fgColor="FFEB9C")   # not measured / needs checking

pre_data  = {r["variant"]: r for r in csv.DictReader(
    (ENV / "logs" / "impl_retime_preswap_full.csv").open())}
# frozen snapshot of the post-swap pass.  logs/impl_retime.csv is the LIVE
# measurement file and gets regenerated by every later sweep, so reading it
# here silently back-dated new results into the swap rows.
post_data = {r["variant"]: r for r in csv.DictReader(
    (ENV / "logs" / "soc_postswap.csv").open())}
plan      = {p["variant"]: p for p in json.load((ENV / "logs" / "swap_plan.json").open())}

shutil.copy(SRC, DST)
wb = openpyxl.load_workbook(DST)

num = lambda v: float(v) if v not in (None, "", "None") else None
soc_rows, headroom, failing = [], [], []

def write_row(ws, row, d, image, when, is_post):
    """Write one SoC row and colour its Fmax by timing outcome."""
    for key, col in COL.items():
        if key == "note":
            continue
        src_key = "fmax_mhz" if key == "fmax" else key
        raw = d.get(src_key)
        if raw in (None, "", "None"):
            continue
        ws[f"{col}{row}"] = (float(raw) if key.startswith("p_") or key == "fmax"
                             else int(float(raw)))
    fmax = float(d["fmax_mhz"])
    clk  = float(d["constraint_mhz"]) if d.get("constraint_mhz") else None
    wns  = float(d["wns_ns"]) if d.get("wns_ns") not in (None, "", "None") else None
    head = (fmax - clk) if clk is not None else None
    tag  = ""
    # hold the PatternFill in a local: reading back cell.fill yields a StyleProxy,
    # which openpyxl cannot assign to another cell
    if wns is not None and wns < 0:
        fill = RED
        tag = (f"  ||  TIMING NOT MET at {clk} MHz (WNS {wns:+.3f} ns) - the design only "
               f"closes at {fmax:.2f} MHz; needs a slower image or re-timing")
    elif head is not None and head > 1.0:
        fill = BLUE
        tag = (f"  ||  HEADROOM +{head:.2f} MHz - runs at {clk} MHz but closes at "
               f"{fmax:.2f} MHz; a faster .mem image is worth building")
    else:
        fill = GREEN
    ws[f"J{row}"].fill = fill
    ws[f"U{row}"] = f"{when}; image {image}" + (
        f"; clock {clk} MHz, WNS {wns:+.3f} ns" if wns is not None else "") + tag
    ws[f"U{row}"].fill = fill          # memo carries the same status colour
    return head, wns

for v, (sheet, row) in PRE.items():
    ws = wb[sheet]
    # --- pre-swap row (2026-09-08) ---
    d = pre_data[v]
    d = {**d, "constraint_mhz": pre_clk.get(v), "wns_ns": pre_wns.get(v)}
    h, w = write_row(ws, row, d, plan[v]["cur"],
                     "measured 2026-09-08 on the fully-verified RTL", False)
    soc_rows.append((v, sheet, row))
    if w is not None and w < 0:
        failing.append((f"{v} [{sheet[-1]}:r{row}]", pre_clk[v], float(d["fmax_mhz"]), h))
    elif h is not None and h > 1.0:
        headroom.append((f"{v} [{sheet[-1]}:r{row}]", pre_clk[v], float(d["fmax_mhz"]), h))
    # --- post-swap row (2026-09-09), mirrored block ---
    if plan[v]["action"] != "swap":
        prow = mirror(row)
        ws[f"J{prow}"].fill = GREY
        ws[f"U{prow}"] = ("NOT measured - this variant was not swapped (no benchmark image "
                          "exists at or below its Fmax), so it has never run this benchmark "
                          "on the fixed RTL.  || " + (ws[f"U{prow}"].value or ""))
        ws[f"U{prow}"].fill = GREY
        continue
    prow = mirror(row)
    h, w = write_row(ws, prow, post_data[v], plan[v]["tgt"],
                     "measured 2026-09-09 after the benchmark swap", True)
    soc_rows.append((v, sheet, prow))
    if w is not None and w < 0:
        failing.append((f"{v} [{sheet[-1]}:r{prow}]", float(post_data[v]["constraint_mhz"]),
                        float(post_data[v]["fmax_mhz"]), h))
    elif h is not None and h > 1.0:
        headroom.append((f"{v} [{sheet[-1]}:r{prow}]", float(post_data[v]["constraint_mhz"]),
                         float(post_data[v]["fmax_mhz"]), h))

# ------------------------------------------------- latest layer (2026-09-09 pm)
# After the swap, every violating or over-relaxed row was re-imaged at a
# frequency it can actually hold, sweeping until it converged.  These
# measurements supersede both earlier passes wherever they exist.
ORDER8 = ["I_5SP", "IM_5SP", "IM_6SP", "IM_7SP", "IM_7SP_BRAM",
          "IM_7SP_BRAM_Opt", "IM_8SP_withoutOpt", "IM_8SP"]
def place(variant, bench):
    sheet = "Sheet1" if variant.startswith("RV64") else "Sheet2"
    short = variant.replace("RV64", "").replace("RV32", "")
    idx = ORDER8.index(short)
    return sheet, (13 if bench == "dhrystone" else 23) + idx

# headroom that exists but cannot be used, with the reason
UNREACHABLE = {
    "RV32IM_8SP": "constraining to 121 MHz yields a WORSE implementation (closes at "
                  "119.0), so this margin is not reachable - 119 MHz is the real limit",
}

latest_csv = ENV / "logs" / "soc_latest.csv"
n_latest = 0
if latest_csv.is_file():
    for d in csv.DictReader(latest_csv.open()):
        sheet, row = place(d["variant"], d["bench"])
        ws = wb[sheet]
        clk, wns = float(d["constraint_mhz"]), float(d["wns_ns"])
        fmax = float(d["fmax_mhz"]); head = fmax - clk
        for key, col in COL.items():
            if key == "note":
                continue
            raw = d.get("fmax_mhz" if key == "fmax" else key)
            if raw in (None, "", "None"):
                continue
            ws[f"{col}{row}"] = (float(raw) if key.startswith("p_") or key == "fmax"
                                 else int(float(raw)))
        if wns < 0:
            fill = RED
            tag = (f"  ||  TIMING NOT MET at {clk:g} MHz (WNS {wns:+.3f} ns) - closes only "
                   f"at {fmax:.2f} MHz")
        elif head > 1.0 and d["variant"] in UNREACHABLE:
            fill = GREEN
            tag = f"  ||  closes at {fmax:.2f} MHz but {UNREACHABLE[d['variant']]}"
        elif head > 1.0:
            fill = BLUE
            tag = (f"  ||  HEADROOM +{head:.2f} MHz - runs at {clk:g} MHz but closes at "
                   f"{fmax:.2f} MHz; a faster .mem image is worth building")
        else:
            fill = GREEN
            tag = ""
        ws[f"J{row}"].fill = fill
        when = ("PLL added 2026-09-10 and re-implemented" if d["variant"] == "RV64IM_8SP"
                and d["bench"] == "dhrystone" else
                "re-imaged and re-implemented 2026-09-09 to a frequency it can hold")
        extra = ""
        if d["variant"] == "RV64IM_8SP" and d["bench"] == "dhrystone":
            extra = ("  ||  was board-clocked at 100 MHz with no MMCM; a PLL was added "
                     "2026-09-10 (M/D/O 51/5/10 = exactly 102.000 MHz) and the image matches "
                     "that frequency. Full Performance_ExplorePostRoutePhysOpt run, "
                     "incremental flow disabled, so it is comparable to the other 15 variants.")
        ws[f"U{row}"] = (f"{when}; image {d['image']}; core clock {d['core_clk']} constrained "
                         f"{clk:g} MHz, WNS {wns:+.3f} ns" + tag + extra)
        ws[f"U{row}"].fill = fill
        n_latest += 1

# ------------------------------------------------------------------- core block
# Core-only synthesis of the memory-externalised *_CORE top, every variant at the
# same 5 ns constraint.  Memory is OUT of these numbers, which is what makes the
# area figures comparable across variants -- unlike the SoC totals, where the
# 5SP/6SP designs hold memory in LUTRAM and the BRAM/8SP designs in block RAM.
# There is no Dhrystone/Coremark split here: with memory externalised the result
# does not depend on which image the SoC project happens to hold.
CORE_CSV = ENV / "logs" / "core_synth.csv"
CORE_ROWS = {  # sheet -> rows 3..10, in the order the sheet lists them
    "Sheet1": ["RV64I_5SP", "RV64IM_5SP", "RV64IM_6SP", "RV64IM_7SP", "RV64IM_7SP_BRAM",
               "RV64IM_7SP_BRAM_Opt", "RV64IM_8SP_withoutOpt", "RV64IM_8SP"],
    "Sheet2": ["RV32I_5SP", "RV32IM_5SP", "RV32IM_6SP", "RV32IM_7SP", "RV32IM_7SP_BRAM",
               "RV32IM_7SP_BRAM_Opt", "RV32IM_8SP_withoutOpt", "RV32IM_8SP"],
}
CORE_COL = dict(fmax="J", p_clocks="M", p_signals="N", p_logic="O", p_bram="P",
                p_dsp="Q", p_io="R", p_static="S", lut="T", ff="U", dsp="V", note="W")

core = {}
if CORE_CSV.is_file():
    core = {r["variant"]: r for r in csv.DictReader(CORE_CSV.open())}

core_done, core_skipped = [], []
for sheet, names in CORE_ROWS.items():
    ws = wb[sheet]
    for i, v in enumerate(names):
        row = 3 + i
        d = core.get(v)
        if not d or d.get("status") != "ok":
            core_skipped.append(f"{v} ({d.get('status') if d else 'no data'})")
            ws[f"{CORE_COL['fmax']}{row}"].fill = GREY
            ws[f"{CORE_COL['note']}{row}"].fill = GREY
            prev = ws[f"{CORE_COL['note']}{row}"].value or ""
            ws[f"{CORE_COL['note']}{row}"] = (
                "NOT re-synthesized 2026-09-08 -- earlier values retained.  || " + prev)
            continue
        for key, col in CORE_COL.items():
            if key == "note":
                continue
            raw = d["fmax_mhz" if key == "fmax" else key]
            if raw in (None, "", "None"):
                continue
            ws[f"{col}{row}"] = float(raw) if key.startswith("p_") or key == "fmax" else int(raw)
        ws[f"{CORE_COL['fmax']}{row}"].fill = GREEN
        ws[f"{CORE_COL['note']}{row}"].fill = GREEN
        ws[f"{CORE_COL['note']}{row}"] = (
            f"core-only re-synth 2026-09-08 on the fully-verified RTL; top {d['top']}; "
            f"all variants at the same {d['constraint_mhz']} MHz (5 ns) constraint, "
            f"WNS {float(d['wns_ns']):+.3f} ns; memory externalised so area excludes ROM/RAM; "
            f"power is POST-SYNTHESIS (routing estimated) and is NOT comparable to the "
            f"SoC post-route power below")
        core_done.append(v)

# ------------------------------------------------ authoritative timing layer
# bitstream/MANIFEST.csv is generated from the implementations that actually
# produced the shipped bitstreams, so it is the final word on clock/WNS/Fmax.
# Earlier layers (retime, swap, reimage) predate the frequency sweep and the
# finalize runs and are stale for any row those touched.
MAN = ENV.parent / "bitstream" / "MANIFEST.csv"
n_time = 0
if MAN.is_file():
    man = {(r["variant"], r["benchmark"]): r for r in csv.DictReader(MAN.open())}
    for sheet in ("Sheet1", "Sheet2"):
        ws = wb[sheet]
        for bench, base in (("dhrystone", 13), ("coremark", 23)):
            for i, short in enumerate(ORDER8):
                row = base + i
                pfx = "RV64" if sheet == "Sheet1" else "RV32"
                d = man.get((pfx + short, bench))
                if not d:
                    continue
                clk, wns = float(d["clock_mhz"]), float(d["wns_ns"])
                fmax = float(d["fmax_mhz"]); head = fmax - clk
                ws[f"J{row}"] = fmax
                if wns < 0:
                    fill = RED
                    tag = (f"  ||  TIMING NOT MET at {clk:g} MHz (WNS {wns:+.3f} ns); "
                           f"closes at {fmax:.2f} MHz")
                elif head > 1.0 and (pfx + short) in UNREACHABLE:
                    fill = GREEN
                    tag = f"  ||  closes at {fmax:.2f} MHz but {UNREACHABLE[pfx+short]}"
                elif head > 1.0:
                    fill = BLUE
                    tag = (f"  ||  HEADROOM +{head:.2f} MHz - runs at {clk:g} MHz, closes "
                           f"at {fmax:.2f} MHz")
                else:
                    fill = GREEN; tag = ""
                ws[f"J{row}"].fill = fill
                ws[f"U{row}"] = (f"final implementation (the one that produced "
                    f"{d['bitstream']}); core clock {clk:g} MHz, WNS {wns:+.3f} ns, "
                    f"closes at {fmax:.2f} MHz; UART BAUD_DIV {d['baud_div']}" + tag)
                ws[f"U{row}"].fill = fill
                n_time += 1

# --------------------------------------------------- SAIF activity-based power
# Vectorless power assumes a uniform 12.5% toggle rate on every net.  These
# columns come from switching activity captured in simulation while the core
# actually runs the benchmark, which is what R1.6/R2.6 asked for.
SAIF_CSV = ENV / "logs" / "saif_power.csv"
SAIF_COL = dict(dyn="X", total="Y", delta="Z", tog="AA")
n_saif = 0
if SAIF_CSV.is_file():
    saif = {(r["variant"], r["bench"]): r for r in csv.DictReader(SAIF_CSV.open())}
    for sheet in ("Sheet1", "Sheet2"):
        ws = wb[sheet]
        for bench, base in (("dhrystone", 13), ("coremark", 23)):
            ws[f"{SAIF_COL['dyn']}{base-1}"]   = "SAIF dynamic W"
            ws[f"{SAIF_COL['total']}{base-1}"] = "SAIF total W"
            ws[f"{SAIF_COL['delta']}{base-1}"] = "vs vectorless"
            ws[f"{SAIF_COL['tog']}{base-1}"]   = "nets toggling %"
            for c in SAIF_COL.values():
                ws[f"{c}{base-1}"].font = Font(bold=True)
            for i, short in enumerate(ORDER8):
                row = base + i
                pfx = "RV64" if sheet == "Sheet1" else "RV32"
                d = saif.get((pfx + short, bench))
                if not d:
                    continue
                ws[f"{SAIF_COL['dyn']}{row}"]   = float(d["saif_dyn"])
                ws[f"{SAIF_COL['total']}{row}"] = float(d["saif_total"])
                ws[f"{SAIF_COL['delta']}{row}"] = float(d["dyn_delta_pct"]) / 100.0
                ws[f"{SAIF_COL['delta']}{row}"].number_format = "+0.0%;-0.0%"
                ws[f"{SAIF_COL['tog']}{row}"]   = float(d["toggling_pct"]) / 100.0
                ws[f"{SAIF_COL['tog']}{row}"].number_format = "0.0%"
                prev = ws[f"U{row}"].value or ""
                ws[f"U{row}"] = (prev + "  ||  SAIF 2026-09-13: activity-based dynamic "
                    f"{float(d['saif_dyn']):.3f} W vs vectorless {float(d['vect_dyn']):.3f} W "
                    f"({float(d['dyn_delta_pct']):+.1f}%); post-implementation netlist simulation "
                    f"without SDF (glitch power excluded); {float(d['toggling_pct']):.1f}% of nets "
                    f"toggling in the captured window")
                n_saif += 1

# ------------------------------------------------------------------ legend
# The 2026-09-08 caveats belong with the data, in each sheet's existing legend
# block, rather than on a separate summary sheet.
LEGEND = [
    ("no fill",    "timing met with less than 1 MHz of headroom - nothing to do"),
    ("red Fmax",   "timing VIOLATION: negative setup slack at the configured clock.  "
                   "The Fmax column is the frequency the design actually closes at; it "
                   "needs an image at or below that, or re-timing."),
    ("blue Fmax",  "timing met but the design closes MORE THAN 1 MHz above the clock it "
                   "is running at -- a faster .mem image is worth building.  The note in "
                   "column U gives the achievable frequency."),
    ("yellow Fmax", "NOT measured, or needs checking.  For a SoC row this means the project "
                   "currently holds the other benchmark image; its Fmax still comes from "
                   "the old board-clock calculation and is NOT comparable to the "
                   "green/red rows."),
    ("SoC Fmax",   "measured on the CORE clock (the clock-wizard output that captures "
                   "logic), NOT the 100 MHz board clock, as 1000/(period - WNS).  Earlier "
                   "sweeps divided every design's slack by the board clock's 10 ns period, "
                   "which compressed all 16 variants into a false 95-102 MHz band and "
                   "inverted the 7SP_BRAM vs 7SP_BRAM_Opt ordering.  Those figures are void."),
    ("SoC LUT",    "NOT comparable across variants: the 5SP/6SP designs hold ROM/RAM in "
                   "LUTRAM, the BRAM/8SP designs in block RAM, so most of the apparent LUT "
                   "collapse is memory relocating rather than the pipeline shrinking.  Use "
                   "the core block (rows 3-10) for any area claim; use the SoC blocks for "
                   "the BRAM/DSP accounting."),
    ("core block", "rows 3-10: out-of-context synthesis of the memory-externalised *_CORE "
                   "top, every variant at the SAME 5 ns (200 MHz) constraint, so "
                   "Fmax = 1000/(5 - WNS) and cross-variant comparison is valid.  Negative "
                   "WNS at 5 ns is expected -- no variant targets 200 MHz.  POST-SYNTHESIS: "
                   "routing estimated, so not comparable to the SoC post-route numbers."),
    ("SoC blocks", "each project holds ONE benchmark image and the image changes the "
                   "design, which is why Dhrystone and Coremark are separate blocks.  Every "
                   "project was measured on 2026-09-08 with the image it then held, swapped "
                   "to the other benchmark, and measured again on 2026-09-09 -- so both "
                   "blocks carry real measurements.  The image is named in column U."),
    ("image effect", "the benchmark image changes timing only where the ROM is in LUTRAM "
                   "(5SP/6SP and 7SP non-BRAM): there it is logic, so the netlist and timing "
                   "move.  On BRAM designs it is only block-RAM initialisation, so the "
                   "netlist is unchanged -- RV32IM_8SP and RV32IM_8SP_withoutOpt came back "
                   "bit-identical, same LUTs and same WNS."),
    ("power",      "Vivado VECTORLESS estimation (no SAIF).  report_power rounds each "
                   "category to 3 dp, so the category columns can sum to up to 2 mW below "
                   "the total Vivado reports; the values are as measured."),
]
for sheet in ("Sheet1", "Sheet2"):
    ws = wb[sheet]
    row = 33
    ws[f"B{row}"] = "Legend"
    ws[f"B{row}"].font = Font(bold=True)
    ws[f"C{row}"] = f"revised {datetime.date.today().isoformat()}"
    for label, text in LEGEND:
        row += 1
        ws[f"B{row}"] = label
        ws[f"C{row}"] = text
        ws[f"C{row}"].alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[row].height = 30
    # clear any leftover rows from the previous, shorter legend
    for r in range(row + 1, 45):
        for col in "BC":
            ws[f"{col}{r}"] = None
    ws[f"B{row+2}"] = ("RV64IM_8SP has no MMCM: it is clocked directly by the 100 MHz board "
                       "pin, so for that variant alone the board clock IS the core clock.")
    ws[f"B{row+3}"] = ("RV64I_5SP was not re-implemented 2026-09-08 (project locked); its RTL "
                       "is unchanged since 2026-09-02 -- I-only and 5-stage, so none of the "
                       "four RTL fixes touch it -- and those SoC results remain valid.")
    ws.column_dimensions["C"].width = max(ws.column_dimensions["C"].width or 10, 100)

wb.save(DST)
print(f"updated {DST}")
print(f"  core block: {len(core_done)}/16 re-synthesized"
      + (f", skipped: {core_skipped}" if core_skipped else ""))
print(f"  SoC blocks: {len(soc_rows)}/32 rows carry measured data, "
      f"{n_latest} superseded by the 2026-09-09 sweep")
if failing:
    print(f"  TIMING NOT MET ({len(failing)} rows) - red:")
    for v, c, f, h in sorted(failing, key=lambda x: x[3]):
        print(f"    {v:<32} runs {c:>8} MHz, closes at {f:6.2f}  ({h:+.2f})")
if headroom:
    print(f"  HEADROOM >1 MHz ({len(headroom)}) - blue, build a faster .mem:")
    for v, c, f, h in sorted(headroom, key=lambda x: -x[3]):
        print(f"    {v:<32} runs {c:>8} MHz, closes at {f:6.2f}  (+{h:.2f})")
