#!/usr/bin/env python3
"""Emit one riscv-config ISA yaml per ISA configuration.

Four configurations cover all 14 variants: RV32I, RV32IM, RV64I, RV64IM, each
with Zicsr.  Every value below was read out of the corresponding CSR_File.v
rather than assumed -- misa, mstatus and the ID registers all differ between
the RV32 and RV64 families, and the RV32 cores additionally implement the high
halves of the counters plus mimpid.

RISCOF uses the declared ISA to pick which tests run, so these files are what
makes the sweep self-selecting: an RV32I core is never handed an M test.
"""
import os

OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..",
                                   "plugins", "rv_im100", "isa"))

CONFIGS = {
    "rv32i": dict(
        isa="RV32IZicsr", xlen=32, paddr=32,
        misa=0x40000100, ext_legal=0x00000100, mxl=0x1,
        mstatus=0x00001800, mtvec=0x00006D60,
        # mvendorid is a 32-bit register at every MXLEN.
        mvendorid=0x52564B43, marchid=0x34365335,
        mimpid=0x34364931, mhartid=0x524B4330,
    ),
    "rv32im": dict(
        isa="RV32IMZicsr", xlen=32, paddr=32,
        misa=0x40001100, ext_legal=0x00001100, mxl=0x1,
        mstatus=0x00001800, mtvec=0x00006D60,
        mvendorid=0x52564B43, marchid=0x34365335,
        mimpid=0x34364931, mhartid=0x524B4330,
    ),
    "rv64i": dict(
        isa="RV64IZicsr", xlen=64, paddr=56,
        misa=0x8000000000000100, ext_legal=0x00000100, mxl=0x2,
        mstatus=0x0000000000001800, mtvec=0x00006D60,
        # The RTL drives a 64-bit constant into mvendorid; only the low 32
        # bits are architecturally defined, so that is what is declared here.
        mvendorid=0x2D4B4321, marchid=0x52563634494D3539,
        mimpid=None, mhartid=0x42414E414E414E41,
    ),
    "rv64im_rtos8": dict(
        isa="RV64IMZicsr", xlen=64, paddr=56,
        misa=0x8000000000001100, ext_legal=0x00001100, mxl=0x2,
        mstatus=0x0000000000001800, mtvec=0x00006D60,
        # mvendorid is 32-bit; the RTL drives the ASCII string "piveline".
        mvendorid=0x6C696E65, marchid=0x52563634494D3732,
        mimpid=None, mhartid=0x0,
        mscratch=True, mstatus_mie=True,
    ),
    "rv64im": dict(
        isa="RV64IMZicsr", xlen=64, paddr=56,
        misa=0x8000000000001100, ext_legal=0x00001100, mxl=0x2,
        mstatus=0x0000000000001800, mtvec=0x00006D60,
        mvendorid=0x2D4B4321, marchid=0x52563634494D3732,
        mimpid=None, mhartid=0x42414E414E414E41,
    ),
}


def build(c):
    x = c["xlen"]
    this = "rv32" if x == 32 else "rv64"
    other = "rv64" if x == 32 else "rv32"
    pad = x // 4
    nib = "f" * pad
    L = []
    w = L.append

    w("# Generated by scripts/gen_isa_yaml.py -- values read from CSR_File.v\n")
    w("hart_ids: [0]\n")
    w("hart0:\n")
    w("  ISA: %s\n" % c["isa"])
    w("  physical_addr_sz: %d\n" % c["paddr"])
    w('  User_Spec_Version: "2.2"\n')
    w("  supported_xlen: [%d]\n\n" % x)

    w("  misa:\n")
    w("    reset-val: 0x%0*X\n" % (pad, c["misa"]))
    w("    %s:\n      accessible: false\n" % other)
    w("    %s:\n      accessible: true\n" % this)
    w("      mxl:\n        implemented: true\n        type:\n          warl:\n")
    w("            dependency_fields: []\n            legal:\n")
    w('              - "mxl[1:0] in [0x%X]"\n' % c["mxl"])
    w('            wr_illegal:\n              - "unchanged"\n')
    w("      extensions:\n        implemented: true\n        type:\n          warl:\n")
    w("            dependency_fields: []\n            legal:\n")
    w('              - "extensions[25:0] in [0x%08X]"\n' % c["ext_legal"])
    w('            wr_illegal:\n              - "unchanged"\n\n')

    # mstatus is a constant wire in the RTL: MPP is fixed at M, nothing else
    # is even implemented.
    w("  mstatus:\n")
    w("    reset-val: 0x%0*X\n" % (pad, c["mstatus"]))
    w("    %s:\n      accessible: false\n" % other)
    w("    %s:\n      accessible: true\n" % this)
    w("      mpp:\n        implemented: true\n        type:\n          warl:\n")
    w("            dependency_fields: []\n            legal:\n")
    w('              - "mpp[1:0] in [0x3]"\n')
    w('            wr_illegal:\n              - "unchanged"\n')
    if c.get("mstatus_mie"):
        # MIE/MPIE are real state on this design: mstatus is assembled from
        # them rather than being a constant wire.
        for f in ("mie", "mpie"):
            w("      %s:\n        implemented: true\n" % f)
        for f in ("sie", "spie"):
            w("      %s:\n        implemented: false\n" % f)
    else:
        for f in ("mie", "mpie", "sie", "spie"):
            w("      %s:\n        implemented: false\n" % f)
    w("\n")

    w("  mtvec:\n")
    w("    reset-val: 0x%0*X\n" % (pad, c["mtvec"]))
    w("    %s:\n      accessible: false\n" % other)
    w("    %s:\n      accessible: true\n" % this)
    w("      base:\n        implemented: true\n        type:\n          warl:\n")
    w("            dependency_fields: []\n            legal:\n")
    w('              - "base[%d:0] in [0x%s:0x%s]"\n'
      % (x - 3, "0" * (pad - 1) + "0", "3" + "f" * (pad - 1)))
    w('            wr_illegal:\n              - "unchanged"\n')
    w("      mode:\n        implemented: true\n        type:\n          warl:\n")
    w("            dependency_fields: []\n            legal:\n")
    w('              - "mode[1:0] in [0x0]"\n')
    w('            wr_illegal:\n              - "unchanged"\n\n')

    w("  mepc:\n    reset-val: 0x0\n")
    w("    %s:\n      accessible: false\n" % other)
    w("    %s:\n      accessible: true\n" % this)
    w("      type:\n        warl:\n          dependency_fields: []\n          legal:\n")
    w('            - "mepc[%d:0] in [0x%s:0x%s]"\n' % (x - 1, "0" * pad, nib))
    w('          wr_illegal:\n            - "unchanged"\n\n')

    w("  mcause:\n    reset-val: 0x0\n")
    w("    %s:\n      accessible: false\n" % other)
    w("    %s:\n      accessible: true\n" % this)
    w("      interrupt:\n        implemented: true\n")
    w("      exception_code:\n        implemented: true\n")
    w('        type:\n          wlrl:\n            - "0:15"\n\n')

    if c.get("mscratch"):
        w("  mscratch:\n    reset-val: 0x0\n")
        w("    %s:\n      accessible: false\n" % other)
        w("    %s:\n      accessible: true\n" % this)
        w("      type:\n        warl:\n          dependency_fields: []\n          legal:\n")
        w('            - "mscratch[%d:0] in [0x%s:0x%s]"\n' % (x - 1, "0" * pad, nib))
        w('          wr_illegal:\n            - "unchanged"\n\n')

    counters = ["mcycle", "minstret"]
    if x == 32:
        counters += ["mcycleh", "minstreth"]
    for name in counters:
        w("  %s:\n" % name)
        w("    %s:\n      accessible: false\n" % other)
        w("    %s:\n      accessible: true\n\n" % this)

    ids = [("mvendorid", c["mvendorid"]), ("marchid", c["marchid"])]
    if c["mimpid"] is not None:
        ids.append(("mimpid", c["mimpid"]))
    ids.append(("mhartid", c["mhartid"]))
    for name, val in ids:
        w("  %s:\n" % name)
        w("    reset-val: 0x%X\n" % val)
        w("    %s:\n      accessible: false\n" % other)
        w("    %s:\n      accessible: true\n\n" % this)

    return "".join(L)


PLATFORM = """# Generated by scripts/gen_isa_yaml.py
mtime:
  implemented: false
mtimecmp:
  implemented: false
nmi:
  label: nmi_vector
reset:
  label: _start
"""

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for key, c in CONFIGS.items():
        p = os.path.join(OUT, "%s_isa.yaml" % key)
        with open(p, "w") as fh:
            fh.write(build(c))
        print("wrote", p)
    p = os.path.join(OUT, "platform.yaml")
    with open(p, "w") as fh:
        fh.write(PLATFORM)
    print("wrote", p)
