#!/usr/bin/env python3
"""Drive RISCOF over the RV-IM100 variants.

Generates a config.ini per variant and invokes `riscof run` once per test group
(I, and M where the core has the extension).  The reference model is the Sail
RISC-V C emulator in every case.

Usage:
    scripts/run.py                      # every variant, every applicable group
    scripts/run.py RV64IM_8SP           # one variant
    scripts/run.py RV64IM_8SP --group I # one variant, one group
"""
import argparse
import os
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from variants import all_variants  # noqa: E402

ENV = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SUITE_ROOT = "/home/khwl/riscv-arch-test/riscv-test-suite"
SAIL_BIN = "/home/khwl/Downloads/sail-riscv-riscof-0.6/c_emulator"
RV32_TOOLS = "/home/khwl/riscv32i-elf/bin"
RV64_TOOLS = "/opt/riscv/bin"
VERILATOR = "/home/khwl/tools/verilator/bin"

CONFIG = """# Generated by scripts/run.py for {variant}
[RISCOF]
ReferencePlugin=sail_cSim
ReferencePluginPath={env}/plugins/sail_cSim
DUTPlugin=rv_im100
DUTPluginPath={env}/plugins/rv_im100

[rv_im100]
pluginpath={env}/plugins/rv_im100
ispec={env}/plugins/rv_im100/isa/{cfg}_isa.yaml
pspec={env}/plugins/rv_im100/isa/platform.yaml
dut_exe={env}/build/{variant}/Vsim_top
variant={variant}
cross_prefix=riscv64-unknown-elf-
max_cycles=200000000
timeout=1800

[sail_cSim]
pluginpath={env}/plugins/sail_cSim
PATH={sail}
jobs={jobs}
"""


def cfg_name(v):
    return v.get("cfg") or (("rv%d" % v["xlen"]) + v["ext"].lower())


def groups_for(v):
    return ["I", "M"] if v["ext"] == "IM" else ["I"]


def suite_dir(v, group):
    fam = "rv32i_m" if v["xlen"] == 32 else "rv64i_m"
    return os.path.join(SUITE_ROOT, fam, group)


def write_config(v, jobs):
    d = os.path.join(ENV, "work", v["name"])
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, "config.ini")
    with open(p, "w") as fh:
        fh.write(CONFIG.format(env=ENV, variant=v["name"], cfg=cfg_name(v),
                               sail=SAIL_BIN, jobs=jobs))
    return p


def run_one(v, group, jobs):
    cfg = write_config(v, jobs)
    work = os.path.join(ENV, "work", v["name"], group)
    log = os.path.join(ENV, "logs", "riscof_%s_%s.log" % (v["name"], group))

    env = dict(os.environ)
    env["PATH"] = os.pathsep.join(
        [SAIL_BIN, RV64_TOOLS, RV32_TOOLS, VERILATOR, env.get("PATH", "")])

    cmd = ["riscof", "run", "--config", cfg, "--work-dir", work,
           "--suite", suite_dir(v, group),
           "--env", os.path.join(SUITE_ROOT, "env"),
           "--no-browser"]

    t0 = time.time()
    with open(log, "w") as lf:
        lf.write("$ %s\n\n" % " ".join(cmd))
        lf.flush()
        rc = subprocess.call(cmd, stdout=lf, stderr=subprocess.STDOUT,
                             cwd=ENV, env=env)
    dt = time.time() - t0

    passed, failed = tally(os.path.join(work, "report.html"))
    status = "ok" if rc == 0 else "rc=%d" % rc
    print("  %-22s %-2s  %3d passed  %3d failed  (%5.1fs, %s)"
          % (v["name"], group, passed, failed, dt, status), flush=True)
    return passed, failed


def tally(report):
    if not os.path.isfile(report):
        return 0, 0
    import re
    with open(report, errors="ignore") as fh:
        body = fh.read().split("</script>")[-1]
    return (len(re.findall(r">\s*Passed\s*<", body)),
            len(re.findall(r">\s*Failed\s*<", body)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("variants", nargs="*")
    ap.add_argument("--group", choices=["I", "M", "privilege", "Zifencei"])
    ap.add_argument("--jobs", default=str(max(1, (os.cpu_count() or 4) // 2)))
    args = ap.parse_args()

    todo = [v for v in all_variants()
            if not args.variants or v["name"] in args.variants]
    if not todo:
        sys.exit("no matching variants")

    tot_p = tot_f = 0
    for v in todo:
        groups = [args.group] if args.group else groups_for(v)
        for g in groups:
            p, f = run_one(v, g, args.jobs)
            tot_p += p
            tot_f += f
    print("\ntotal: %d passed, %d failed" % (tot_p, tot_f))
    return 1 if tot_f else 0


if __name__ == "__main__":
    sys.exit(main())
